// autumn-gateway-dashboard-vue/src/views/system/user/detail.vue
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ArrowLeft, UserFilled } from '@element-plus/icons-vue'
import http from '../../../utils/request'
import { copyText, fmtDateTime } from '../../../utils/format'

const route = useRoute()
const router = useRouter()
const userId = route.params.id

const tab = ref('basic')
const loading = ref(false)
const user = ref(null)

// 应用相关
const allApps = ref([])
const selectedAppIds = ref([])

// 角色相关
const allRoles = ref([])
const selectedRoleIds = ref([])
const appMap = ref({})

async function loadUserData() {
  loading.value = true
  try {
    const [userRes, appsRes, userAppsRes, rolesRes, userRolesRes] =
      await Promise.all([
        http.get(`/api/system/user/${userId}`),
        http.get('/api/system/app/list'),
        http.get(`/api/system/user/${userId}/apps`),
        http.get('/api/system/role/list'),
        http.get(`/api/system/user/${userId}/roles`),
      ])
    user.value = userRes.data
    allApps.value = appsRes.data || []
    selectedAppIds.value = (userAppsRes.data || []).map((item) => item.appId)
    allRoles.value = rolesRes.data || []
    selectedRoleIds.value = (userRolesRes.data || []).map((item) => item.roleId)

    const map = {}
    ;(appsRes.data || []).forEach((app) => {
      map[app.id] = app.name
    })
    appMap.value = map
  } catch (e) {
    ElMessage.error('加载用户数据失败')
  } finally {
    loading.value = false
  }
}

// 关联应用表
const appDataSource = computed(() =>
  allApps.value.map((app) => ({
    ...app,
    _associated: selectedAppIds.value.includes(app.id),
  })),
)

// 关联角色表（仅显示已关联应用下的角色）
const roleDataSource = computed(() =>
  allRoles.value
    .filter((role) => selectedAppIds.value.includes(role.appId))
    .map((role) => ({
      ...role,
      _associated: selectedRoleIds.value.includes(role.id),
    })),
)

async function toggleApp(row) {
  const currentlyAssociated = selectedAppIds.value.includes(row.id)
  const newIds = currentlyAssociated
    ? selectedAppIds.value.filter((id) => id !== row.id)
    : [...selectedAppIds.value, row.id]
  try {
    await http.put(`/api/system/user/${userId}/apps`, { appIds: newIds })
    selectedAppIds.value = newIds
    ElMessage.success(currentlyAssociated ? '已解绑应用' : '已关联应用')
  } catch {
    /* 拦截器已提示 */
  }
}

async function toggleRole(row) {
  const currentlyAssociated = selectedRoleIds.value.includes(row.id)
  const newIds = currentlyAssociated
    ? selectedRoleIds.value.filter((id) => id !== row.id)
    : [...selectedRoleIds.value, row.id]
  try {
    await http.put(`/api/system/user/${userId}/roles`, { roleIds: newIds })
    selectedRoleIds.value = newIds
    ElMessage.success(currentlyAssociated ? '已解绑角色' : '已关联角色')
  } catch {
    /* 拦截器已提示 */
  }
}

function back() {
  router.push('/system/user')
}

onMounted(loadUserData)
</script>

<template>
  <div class="pro-page">
    <!-- 页头 -->
    <div class="page-header">
      <div class="page-header-title">
        用户详情 - {{ user?.username || '加载中...' }}
      </div>
      <div>
        <el-button :icon="ArrowLeft" @click="back">返回列表</el-button>
      </div>
    </div>

    <el-tabs v-model="tab" type="border-card">
      <!-- 基本信息 -->
      <el-tab-pane label="基本信息" name="basic">
        <div class="desc-box" v-loading="loading">
          <el-descriptions v-if="user" :column="2" border>
            <el-descriptions-item label="ID">{{ user.id }}</el-descriptions-item>
            <el-descriptions-item label="用户名">{{ user.username }}</el-descriptions-item>
            <el-descriptions-item label="昵称">
              <span class="nickname-cell">
                <el-avatar :size="22" :src="user.avatar">
                  <el-icon><UserFilled /></el-icon>
                </el-avatar>
                {{ user.nickname || '-' }}
              </span>
            </el-descriptions-item>
            <el-descriptions-item label="邮箱">{{ user.email || '-' }}</el-descriptions-item>
            <el-descriptions-item label="手机">{{ user.phone || '-' }}</el-descriptions-item>
            <el-descriptions-item label="员工号">{{ user.empNo || '-' }}</el-descriptions-item>
            <el-descriptions-item label="状态">
              <el-tag :type="user.status === 1 ? 'success' : 'danger'" size="small">
                {{ user.status === 1 ? '正常' : '禁用' }}
              </el-tag>
            </el-descriptions-item>
            <el-descriptions-item label="最后登录">{{ fmtDateTime(user.lastLoginAt) }}</el-descriptions-item>
            <el-descriptions-item label="创建时间">{{ fmtDateTime(user.createdAt) }}</el-descriptions-item>
            <el-descriptions-item label="更新时间">{{ fmtDateTime(user.updatedAt) }}</el-descriptions-item>
          </el-descriptions>
          <el-empty v-else-if="!loading" description="暂无数据" />
        </div>
      </el-tab-pane>

      <!-- 关联应用 -->
      <el-tab-pane label="关联应用" name="apps">
        <div class="pro-card" style="margin-top: 12px">
          <div class="pro-table-wrap">
            <el-table v-loading="loading" :data="appDataSource" row-key="id" stripe>
              <el-table-column prop="id" label="应用ID" width="90" />
              <el-table-column prop="name" label="应用名称" min-width="160" show-overflow-tooltip />
              <el-table-column prop="appid" label="应用标识" min-width="130">
                <template #default="{ row }">
                  <el-tooltip content="点击复制" placement="top">
                    <span class="copy-text" @click="copyText(row.appid)">{{ row.appid }}</span>
                  </el-tooltip>
                </template>
              </el-table-column>
              <el-table-column label="关联状态" width="100" align="center">
                <template #default="{ row }">
                  <el-tag :type="row._associated ? 'success' : 'info'" size="small" effect="plain">
                    {{ row._associated ? '已关联' : '未关联' }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column label="操作" width="90" align="center">
                <template #default="{ row }">
                  <el-link
                    :type="row._associated ? 'danger' : 'primary'"
                    @click="toggleApp(row)"
                  >
                    {{ row._associated ? '解绑' : '关联' }}
                  </el-link>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>

      <!-- 关联角色 -->
      <el-tab-pane label="关联角色" name="roles">
        <div class="pro-card" style="margin-top: 12px">
          <div class="table-hint">角色列表（仅显示已关联应用下的角色）</div>
          <div class="pro-table-wrap">
            <el-table
              v-loading="loading"
              :data="roleDataSource"
              row-key="id"
              stripe
              empty-text="请先关联应用后再分配角色"
            >
              <el-table-column prop="id" label="角色ID" width="90" />
              <el-table-column prop="code" label="角色编码" min-width="140">
                <template #default="{ row }">
                  <el-tooltip content="点击复制" placement="top">
                    <span class="copy-text" @click="copyText(row.code)">{{ row.code }}</span>
                  </el-tooltip>
                </template>
              </el-table-column>
              <el-table-column prop="name" label="角色名称" min-width="150" show-overflow-tooltip />
              <el-table-column label="所属应用" min-width="140" show-overflow-tooltip>
                <template #default="{ row }">{{ appMap[row.appId] || `应用#${row.appId}` }}</template>
              </el-table-column>
              <el-table-column label="关联状态" width="100" align="center">
                <template #default="{ row }">
                  <el-tag :type="row._associated ? 'success' : 'info'" size="small" effect="plain">
                    {{ row._associated ? '已关联' : '未关联' }}
                  </el-tag>
                </template>
              </el-table-column>
              <el-table-column label="操作" width="90" align="center">
                <template #default="{ row }">
                  <el-link
                    :type="row._associated ? 'danger' : 'primary'"
                    @click="toggleRole(row)"
                  >
                    {{ row._associated ? '解绑' : '关联' }}
                  </el-link>
                </template>
              </el-table-column>
            </el-table>
          </div>
        </div>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<style scoped>
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: #fff;
  padding: 16px 24px;
  margin-bottom: 16px;
  border-radius: 8px;
}

.page-header-title {
  font-size: 20px;
  font-weight: 600;
  color: rgba(0, 0, 0, 0.88);
}

.nickname-cell {
  display: inline-flex;
  align-items: center;
  gap: 8px;
}

.table-hint {
  margin-bottom: 12px;
  color: rgba(0, 0, 0, 0.65);
}
</style>

// autumn-gateway-dashboard-ui/src/pages/System/User/Detail/index.tsx
import React, { useState, useCallback, useEffect } from 'react';
import { PageContainer, ProTable } from '@ant-design/pro-components';
import { Tabs, Descriptions, Tag, Button, Space, Spin, message, Empty } from 'antd';
import { history, useParams, request } from '@umijs/max';

const UserDetail: React.FC = () => {
    const params = useParams<{ id: string }>();
    const userId = params.id;

    const [tab, setTab] = useState<string>('basic');
    const [loading, setLoading] = useState<boolean>(true);
    const [user, setUser] = useState<any>(null);

    // 应用相关
    const [allApps, setAllApps] = useState<any[]>([]);
    const [selectedAppIds, setSelectedAppIds] = useState<number[]>([]);

    // 角色相关
    const [allRoles, setAllRoles] = useState<any[]>([]);
    const [selectedRoleIds, setSelectedRoleIds] = useState<number[]>([]);
    const [appMap, setAppMap] = useState<Record<number, string>>({});

    const fetchUserData = useCallback(async () => {
        if (!userId) return;
        setLoading(true);
        try {
            const [userRes, appsRes, userAppsRes, rolesRes, userRolesRes] = await Promise.all([
                request<{ data: any }>(`/api/system/user/${userId}`),
                request<{ data: any[] }>('/api/system/app/list'),
                request<{ data: any[] }>(`/api/system/user/${userId}/apps`),
                request<{ data: any[] }>('/api/system/role/list'),
                request<{ data: any[] }>(`/api/system/user/${userId}/roles`),
            ]);

            setUser(userRes.data);
            setAllApps(appsRes.data || []);
            setSelectedAppIds((userAppsRes.data || []).map((item: any) => item.appId));
            setAllRoles(rolesRes.data || []);
            setSelectedRoleIds((userRolesRes.data || []).map((item: any) => item.roleId));

            // 构建应用名称映射
            const map: Record<number, string> = {};
            (appsRes.data || []).forEach((app: any) => {
                map[app.id] = app.name;
            });
            setAppMap(map);
        } catch (error) {
            message.error('加载用户数据失败');
        } finally {
            setLoading(false);
        }
    }, [userId]);

    useEffect(() => {
        if (userId) {
            fetchUserData();
        }
    }, [userId, fetchUserData]);

    // 切换应用关联状态
    const toggleApp = async (appId: number, currentlyAssociated: boolean) => {
        let newIds: number[];
        if (currentlyAssociated) {
            newIds = selectedAppIds.filter(id => id !== appId);
        } else {
            newIds = [...selectedAppIds, appId];
        }
        try {
            await request(`/api/system/user/${userId}/apps`, {
                method: 'PUT',
                data: { appIds: newIds },
            });
            setSelectedAppIds(newIds);
            message.success(currentlyAssociated ? '已解绑应用' : '已关联应用');
        } catch {
            message.error('操作失败');
        }
    };

    // 切换角色关联状态
    const toggleRole = async (roleId: number, currentlyAssociated: boolean) => {
        let newIds: number[];
        if (currentlyAssociated) {
            newIds = selectedRoleIds.filter(id => id !== roleId);
        } else {
            newIds = [...selectedRoleIds, roleId];
        }
        try {
            await request(`/api/system/user/${userId}/roles`, {
                method: 'PUT',
                data: { roleIds: newIds },
            });
            setSelectedRoleIds(newIds);
            message.success(currentlyAssociated ? '已解绑角色' : '已关联角色');
        } catch {
            message.error('操作失败');
        }
    };

    if (!userId) return <Empty description="用户ID不能为空" />;

    // 应用表格列
    const appColumns = [
        { title: '应用ID', dataIndex: 'id', width: 80 },
        { title: '应用名称', dataIndex: 'name', ellipsis: true },
        { title: '应用标识', dataIndex: 'appid', ellipsis: true },
        {
            title: '关联状态',
            dataIndex: 'id',
            render: (id: number) => {
                const isAssociated = selectedAppIds.includes(id);
                return <Tag color={isAssociated ? 'green' : 'default'}>{isAssociated ? '已关联' : '未关联'}</Tag>;
            },
        },
        {
            title: '操作',
            dataIndex: 'id',
            render: (id: number) => {
                const isAssociated = selectedAppIds.includes(id);
                return (
                    <a onClick={() => toggleApp(id, isAssociated)} style={{ color: isAssociated ? '#ff4d4f' : '#1890ff' }}>
                        {isAssociated ? '解绑' : '关联'}
                    </a>
                );
            },
        },
    ];

    // 角色表格列
    const roleColumns = [
        { title: '角色ID', dataIndex: 'id', width: 80 },
        { title: '角色编码', dataIndex: 'code', ellipsis: true },
        { title: '角色名称', dataIndex: 'name', ellipsis: true },
        {
            title: '所属应用',
            dataIndex: 'appId',
            render: (appId: number) => appMap[appId] || `应用#${appId}`,
        },
        { title: '层级', dataIndex: 'level', width: 60 },
        {
            title: '关联状态',
            dataIndex: 'id',
            render: (id: number) => {
                const isAssociated = selectedRoleIds.includes(id);
                return <Tag color={isAssociated ? 'green' : 'default'}>{isAssociated ? '已关联' : '未关联'}</Tag>;
            },
        },
        {
            title: '操作',
            dataIndex: 'id',
            render: (id: number) => {
                const isAssociated = selectedRoleIds.includes(id);
                return (
                    <a onClick={() => toggleRole(id, isAssociated)} style={{ color: isAssociated ? '#ff4d4f' : '#1890ff' }}>
                        {isAssociated ? '解绑' : '关联'}
                    </a>
                );
            },
        },
    ];

    return (
        <PageContainer
            header={{
                title: `用户详情 - ${user?.username || '加载中...'}`,
                extra: <Button onClick={() => history.push('/system/user')}>返回列表</Button>,
            }}
        >
            <Spin spinning={loading}>
                <Tabs activeKey={tab} onChange={setTab}>
                    {/* 基本信息 Tab */}
                    <Tabs.TabPane tab="基本信息" key="basic">
                        <div style={{ padding: 24, background: '#fff', borderRadius: 8 }}>
                            {user ? (
                                <Descriptions column={2} bordered>
                                    <Descriptions.Item label="ID">{user.id}</Descriptions.Item>
                                    <Descriptions.Item label="用户名">{user.username}</Descriptions.Item>
                                    <Descriptions.Item label="昵称">{user.nickname || '-'}</Descriptions.Item>
                                    <Descriptions.Item label="邮箱">{user.email || '-'}</Descriptions.Item>
                                    <Descriptions.Item label="手机">{user.phone || '-'}</Descriptions.Item>
                                    <Descriptions.Item label="员工号">{user.empNo || '-'}</Descriptions.Item>
                                    <Descriptions.Item label="状态">
                                        <Tag color={user.status === 1 ? 'green' : 'red'}>
                                            {user.status === 1 ? '正常' : '禁用'}
                                        </Tag>
                                    </Descriptions.Item>
                                    <Descriptions.Item label="最后登录">{user.lastLoginAt || '-'}</Descriptions.Item>
                                    <Descriptions.Item label="创建时间">{user.createdAt}</Descriptions.Item>
                                    <Descriptions.Item label="更新时间">{user.updatedAt}</Descriptions.Item>
                                </Descriptions>
                            ) : '暂无数据'}
                        </div>
                    </Tabs.TabPane>

                    {/* 关联应用 Tab */}
                    <Tabs.TabPane tab="关联应用" key="apps">
                        <ProTable
                            headerTitle="应用列表"
                            rowKey="id"
                            search={false}
                            pagination={{ pageSize: 10 }}
                            request={async () => {
                                const data = allApps.map(app => ({
                                    ...app,
                                    associated: selectedAppIds.includes(app.id),
                                }));
                                return { data, success: true, total: data.length };
                            }}
                            columns={appColumns}
                        />
                    </Tabs.TabPane>

                    {/* 关联角色 Tab - 只显示用户已关联应用下的角色 */}
                    <Tabs.TabPane tab="关联角色" key="roles">
                        <ProTable
                            headerTitle="角色列表（仅显示已关联应用下的角色）"
                            rowKey="id"
                            search={false}
                            pagination={{ pageSize: 10 }}
                            request={async () => {
                                // 关键过滤：只保留 appId 在 selectedAppIds 中的角色
                                const filteredRoles = allRoles.filter(role => selectedAppIds.includes(role.appId));
                                console.log('当前已关联应用ID:', selectedAppIds);
                                console.log('所有角色:', allRoles);
                                console.log('过滤后角色:', filteredRoles);
                                const data = filteredRoles.map(role => ({
                                    ...role,
                                    associated: selectedRoleIds.includes(role.id),
                                }));
                                return { data, success: true, total: data.length };
                            }}
                            columns={roleColumns}
                            locale={{ emptyText: '请先关联应用后再分配角色' }}
                        />
                    </Tabs.TabPane>
                </Tabs>
            </Spin>
        </PageContainer>
    );
};

export default UserDetail;
